spring.application.name=TradeTide
spring.datasource.url=jdbc:mysql://localhost:3306/TradeTideDB
spring.datasource.username=root
spring.datasource.password=Root2000&&
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tradetide9@gmail.com
spring.mail.password=dpwlgzfvoinvsmpt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.oauth2.client.registration.google.client-id=844158462932-mn0vh409lmvii118gnkmk2ld7hm2r4q1.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.client-name=Google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub



// http://localhost:8080/login/oauth2/code/google 